{
  "openapi": "3.0.1",
  "info": {
    "title": "Tutors and Pets",
    "description": "API de tutores e pets",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/tutor": {
      "post": {
        "summary": "POST /tutor",
        "description": "Adicionar novo tutor",
        "tags": [
          "Tutor"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tutor"
              },
              "examples": {
                "tutor": {
                  "value": {
                    "name": "John Doe",
                    "phone": "123456789",
                    "email": "joao@example.com",
                    "password": "123456",
                    "date_of_birth": "1999-01-01T00:00:00.000Z",
                    "zip_code": "12345",
                    "pets": []
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Token inválido"
          },
          "201": {
            "description": "Tutor criado com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Tutor"
                }
              }
            }
          },
          "502": {
            "description": "Falha ao criar tutor"
          }
        }
      }
    },
    "/tutors": {
      "get": {
        "summary": "GET /tutors",
        "description": "Buscar todos os tutores",
        "tags": [
          "Tutor"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Operação bem-sucedida",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Tutor"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tutor/{id}": {
      "delete": {
        "description": "Deletar tutor por ID",
        "tags": [
          "Tutor"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do tutor",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "description": "Atualizar tutor por ID",
        "tags": [
          "Tutor"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do tutor",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tutor"
              },
              "examples": {
                "tutor": {
                  "value": {
                    "name": "Junior Sousa",
                    "phone": "88994953035",
                    "email": "iamjunioru@gmail.com",
                    "password": "123456",
                    "date_of_birth": "2023-01-01T00:00:00.000Z",
                    "zip_code": "63400000",
                    "pets": []
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          },
          "502": {
            "description": "Erro"
          }
        }
      }
    },
    "/pet/{id}": {
      "post": {
        "summary": "POST /pet/{id}",
        "description": "Adicionar novo pet",
        "tags": [
          "Pets"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do tutor",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pets"
              },
              "examples": {
                "Pets": {
                  "value": {
                    "name": "Fluffy",
                    "species": "Dog",
                    "carry": "Red",
                    "weight": "10",
                    "date_of_birth": "2020-01-01T00:00:00.000Z"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Token inválido"
          },
          "201": {
            "description": "Pet criado com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "502": {
            "description": "Falha ao criar pet"
          }
        }
      }
    },
    "/pet/{id}/tutor/{idTutor}": {
      "put": {
        "summary": "PUT /pet/{id}/tutor/{idTutor}",
        "description": "Editar pet",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Pets"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do pet",
            "required": true
          },
          {
            "name": "idTutor",
            "in": "path",
            "description": "ID do tutor",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pets"
              },
              "examples": {
                "Pets": {
                  "value": {
                    "name": "Miguel",
                    "species": "Cat",
                    "carry": "Frajolinha",
                    "weight": "6",
                    "date_of_birth": "2021-06-23T00:00:00.000Z"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Token inválido"
          },
          "201": {
            "description": "Pet atualizado com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "502": {
            "description": "Falha ao atualizar pet"
          }
        }
      },
      "delete": {
        "summary": "DELETE /pet/{id}/tutor/{idTutor}",
        "description": "Deletar pet",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Pets"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do pet",
            "required": true
          },
          {
            "name": "idTutor",
            "in": "path",
            "description": "ID do tutor",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "502": {
            "description": "Falha ao deletar pet"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Tutor": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "date_of_birth": {
            "type": "string"
          },
          "zip_code": {
            "type": "string"
          },
          "pets": {
            "type": "array",
            "items": {}
          }
        }
      },
      "Pets": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "species": {
            "type": "string"
          },
          "carry": {
            "type": "string"
          },
          "weight": {
            "type": "string"
          },
          "date_of_birth": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
